name: Greet and Label on an Issue Opened

on:
  issues:
    types:
      - opened

jobs:
  greet_and_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Greet
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.DEMO_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello, @${{ github.actor }}! Thanks for opening this issue! '
            })

      - name: Add Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.DEMO_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['hacktoberfest'] 
            })
